name: Vending - Deploy IaC Backends (Azure/Github)

on:
  workflow_dispatch: # Run manually
    inputs:
      tf_action:
        description: "Action: Plan, Apply, Destroy"
        required: true
        default: "Plan"
        type: choice
        options:
          - "Plan"
          - "Plan-Apply"
          - "Destroy"

  push: # Commits
    paths:
      - "environments/azure/global/mgt-iac-backends/**"
      - "modules/azure/vending-iac-backend/**"
      - ".github/workflows/azure/vending-iac-backends.yml"
    branches:
      - main
  
  pull_request: # PR
    paths:
      - "environments/azure/global/mgt-iac-backends/**"
      - "modules/azure/vending-iac-backend/**"
      - ".github/workflows/azure/vending-iac-backends.yml"
    branches:
      - main

permissions:
  id-token: write # Required for OIDC auth
  contents: read
  issues: read

jobs:
  deploy-iac-backend:
    name: Deploy IaC Backends
    runs-on: ubuntu-latest
    timeout-minutes: 30  # The entire job will fail if it runs longer than 'x' minutes.
    defaults:
      run: # Set job defaults for 'run' commands.
        working-directory: ./environments/azure/global/mgt-iac-backends
    env:
      # Backend (IaC subscription)
      TF_BACKEND_RG: ${{ vars.TF_BACKEND_RG }} # Backend: Resource Group
      TF_BACKEND_SA: ${{ vars.TF_BACKEND_SA }} # Backend: Storage Account
      TF_BACKEND_CONTAINER: ${{ vars.TF_BACKEND_CONTAINER }} # Backend: Blob Container
      TF_BACKEND_KEY: ${{ vars.TF_BACKEND_KEY }} # Backend: State file name

      # Azure OIDC Auth
      ARM_USE_OIDC: true
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }} # Azure: Tenant ID
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} # Azure: Service Principal ID
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} # Azure: Target subscription for resources.

      # Github PAT Auth
      GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }} # Required by Terraform provider to manage environments.

      # Determine if Plan should run (on commits, PR, plan and plan-apply). 
      RUN_PLAN: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event.inputs.tf_action == 'Plan' || github.event.inputs.tf_action == 'Plan-Apply' }}

      # Determine if Apply should run (only on manual trigger). 
      RUN_APPLY: ${{ github.event.inputs.tf_action == 'Plan-Apply' }}

      # Determine if Destroy should run (only on manual trigger). 
      RUN_DESTROY: ${{ github.event.inputs.tf_action == 'Destroy' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform Init
        timeout-minutes: 5  # This step will fail if it runs longer than 'x' minutes.
        run: |
          terraform init \
          -backend-config="resource_group_name=$TF_BACKEND_RG" 
          -backend-config="storage_account_name=$TF_BACKEND_SA" 
          -backend-config="container_name=$TF_BACKEND_CONTAINER" 
          -backend-config="key=$TF_BACKEND_KEY"

      - name: Terraform Plan
        if: env.RUN_PLAN == 'true'
        timeout-minutes: 5  # This step will fail if it runs longer than 'x' minutes.
        run: |
          terraform plan -out=terraform.tfplan -var-file=terraform.tfvars \
          -var="github_token=$GH_PAT_TOKEN" 
          -var="iac_storage_account_rg=$TF_BACKEND_RG" 
          -var="iac_storage_account_name=$TF_BACKEND_SA" 
          -var="subscription_id_iac=$ARM_SUBSCRIPTION_ID" 
        
      - name: Terraform Apply
        if: env.RUN_APPLY == 'true'
        timeout-minutes: 15 # Fail if it runs longer than 'x' minutes.
        run: |
          terraform apply --auto-approve terraform.tfplan
    
      - name: Terraform Destroy
        if: env.RUN_DESTROY == 'true'
        timeout-minutes: 15 # Fail if it runs longer than 'x' minutes.
        run: |
          terraform destroy --auto-approve -var-file=terraform.tfvars \
          -var="github_token=$GH_PAT_TOKEN" 
          -var="iac_storage_account_rg=$TF_BACKEND_RG" 
          -var="iac_storage_account_name=$TF_BACKEND_SA" 
          -var="subscription_id_iac=$ARM_SUBSCRIPTION_ID" 
